version: "3"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "<YourStrong@Passw0rd>"
      MSSQL_LOG_STATEMENTS: "all"
    ports:
      - "1433:1433"
    networks:
      - databases
networks:
  databases:
